# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 19:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('regNo', models.CharField(max_length=7, verbose_name='Registration Number')),
                ('faculty', models.CharField(choices=[('FES', 'Engineering Sciences'), ('FME', 'Mechanical Engineering'), ('FCSE', 'Computer Sciences and Engineering')], max_length=50)),
                ('camp', models.CharField(choices=[('ANRD', 'Android'), ('WINAPP', 'Windows App'), ('WEB', 'Web Development'), ('IOT', 'Internet of Things'), ('AI', 'Artificial Intelligence and ANN')], max_length=30, verbose_name='Camp')),
                ('previousExperience', models.BooleanField(default=True, verbose_name='Any previous Programming Experience')),
                ('whyjoin', models.CharField(max_length=500, verbose_name="Why do you want to join Developers' Cell")),
                ('languagesKnown', models.CharField(choices=[('C#', 'C#'), ('C++', 'C++'), ('C', 'C'), ('JV', 'Java'), ('ANRD', 'Android'), ('Py', 'Python'), ('RB', 'Ruby'), ('JS', 'Javascript'), ('NJS', 'node.js')], max_length=60, verbose_name='Languages and Frameworks Known')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Executive',
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('camp', models.CharField(choices=[('ANRD', 'Android'), ('WINAPP', 'Windows App'), ('WEB', 'Web Development'), ('IOT', 'Internet of Things'), ('AI', 'Artificial Intelligence and ANN')], max_length=30, verbose_name='Camp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
