# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The groups based on languages taught', max_length=20, verbose_name='Camp')),
            ],
        ),
        migrations.AlterField(
            model_name='developer',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Camps'),
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='camp',
        ),
        migrations.AddField(
            model_name='mentor',
            name='camp',
            field=models.ManyToManyField(to='portal.Camps'),
        ),
    ]
